### ISSUE TITLE
Djnago 1.9 error

### ISSUE THREAD

**Issue by andreyugit** [ui/django-post_office#127]
Hello!

I installed Django 1.9 and last version django-post_office, try run and:

Traceback (most recent call last):
  File "mysite/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 176, in fetch_command
    commands = get_commands()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 71, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

What is the problem?

Thank you!

**Comment by yprez** [comment]
@andreyugit This should be fixed in the latest github version.

@selwin Any chance for a new release?

**Comment by andreyugit** [comment]
![2015-12-12 21-16-04 default preferences](https://cloud.githubusercontent.com/assets/2041192/11762337/4c79e726-a10d-11e5-9e4c-1cdb875fc028.png)

**Comment by andreyugit** [comment]
manage.py check =>

Traceback (most recent call last):
  File "mysite/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/post_office/__init__.py", line 3, in <module>
    from .backends import EmailBackend
  File "/usr/local/lib/python2.7/dist-packages/post_office/backends.py", line 4, in <module>
    from .mail import create
  File "/usr/local/lib/python2.7/dist-packages/post_office/mail.py", line 12, in <module>
    from .models import Email, EmailTemplate, PRIORITY, STATUS
  File "/usr/local/lib/python2.7/dist-packages/post_office/models.py", line 33, in <module>
    class Email(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by selwin** [comment]
Version 2.0.4 is now up on PyPI! Sorry for the wait
