### ISSUE TITLE
Always render will fail on exception when AdminEmailHandler is enabled

### ISSUE THREAD

**Issue by schemacs** [ui/django-post_office#132]
Django logging:

```python
'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        },
}
'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
}
```

```bash
Internal Server Error: /v1/api/test
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/venv/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "venv/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/xxx/code/prj/core/views.py", line 487, in list
    raise Exception("oops")
Exception: oops

Request repr():
<WSGIRequest
path:/v1/api/test,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'csrftoken': 'xxxx',
 'djdt': 'hide',
 'LC_TELEPHONE': 'en_US.UTF-8',
 'LC_TIME': 'en_US.UTF-8',
 'LESSOPEN': '||/usr/bin/lesspipe.sh %s',
 ...
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}> [{'False': False, 'None': None, 'True': True}, {}]
```

the error is following:
```bash
  File "/venv/lib/python2.7/site-packages/post_office/mail.py", line 72, in create
    message = Template(message).render(_context)
  File "/venv/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/venv/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/venv/lib/python2.7/site-packages/django/template/base.py", line 318, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/venv/lib/python2.7/site-packages/django/template/base.py", line 424, in compile_filter
    return FilterExpression(token, self)
  File "/venv/lib/python2.7/site-packages/django/template/base.py", line 640, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '||' from '||'
```

**Comment by yprez** [comment]
I would set a different email backend for AdminEmailHandler. You can adjust the `email_backend` setting to set it to Django's default.

https://docs.djangoproject.com/en/1.9/topics/logging/#id4

Then the admin error emails won't go through post_office at all (which sounds like a good thing in general, since there may be other DB related bugs and such that can prevent them from going out).

**Comment by selwin** [comment]
There's
