### ISSUE TITLE
jsonfield vs django-jsonfield

### ISSUE THREAD

**Issue by gummoe** [ui/django-post_office#182]
The `setup.py` file lists `jsonfield` as a requirement (https://github.com/ui/django-post_office/blob/master/setup.py#L42), but the PyPi page lists `django-jsonfield` as a requirement. 

We recently had a build on Heroku start failing after rebuilding our requirements.txt file from a brand new pip freeze and `django-jsonfield` was not included (`jsonfield` was, naturally). 

Explicitly requiring `django-jsonfield` resolved this problem. So, which dependency is correct? I think that it's `django-jsonfield` at the very least, but maybe it is both?

The build failed with this stack:
`python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "manage.py", line 10, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
           django.setup()
         File "/app/.heroku/python/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
           apps.populate(settings.INSTALLED_APPS)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
           app_config = AppConfig.create(entry)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
           module = import_module(entry)
         File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
           __import__(name)
         File "/app/.heroku/python/lib/python2.7/site-packages/post_office/__init__.py", line 3, in <module>
           from .backends import EmailBackend
         File "/app/.heroku/python/lib/python2.7/site-packages/post_office/backends.py", line 4, in <module>
           from .settings import get_default_priority
         File "/app/.heroku/python/lib/python2.7/site-packages/post_office/settings.py", line 91, in <module>
           context_field_class = import_attribute(CONTEXT_FIELD_CLASS)
         File "/app/.heroku/python/lib/python2.7/site-packages/post_office/compat.py", line 45, in import_attribute
           module = importlib.import_module(module_name)
         File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
           __import__(name)
       ImportError: No module named jsonfield
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.`

**Comment by selwin** [comment]
The library is named django-jsonfield ( https://github.com/bradjasper/django-jsonfield) but it's published as jsonfield on PyPI so you should put "jsonfield" in your pip requirements file.
