### ISSUE TITLE
Running Unit Tests with Python-3.8

### ISSUE THREAD

**Issue by jrief** [ui/django-post_office#319]
With Python up to version 3.7.6 running unit test for django-post_office work just fine.
However, after upgrading to Python-3.8.1 I get this error:

```bash
Started sending 3 emails with 2 processes.
Process SpawnPoolWorker-1:
Process SpawnPoolWorker-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "django-post_office/post_office/mail.py", line 12, in <module>
    from .models import Email, EmailTemplate, Log, PRIORITY, STATUS
  File "django-post_office/post_office/models.py", line 27, in <module>
    class Email(models.Model):
  File "lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "lib/python3.8/site-packages/django/db/models/base.py", line 107, in __new__
    app_config = apps.get_containing_app_config(module)
  File "lib/python3.8/site-packages/django/apps/registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "lib/python3.8/site-packages/django/apps/registry.py", line 135, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
  File "lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
  File "django-post_office/post_office/mail.py", line 12, in <module>
    from .models import Email, EmailTemplate, Log, PRIORITY, STATUS
  File "django-post_office/post_office/models.py", line 27, in <module>
    class Email(models.Model):
  File "lib/python3.8/site-packages/django/db/models/base.py", line 107, in __new__
    app_config = apps.get_containing_app_config(module)
  File "lib/python3.8/site-packages/django/apps/registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "lib/python3.8/site-packages/django/apps/registry.py", line 135, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

This only happens while testing the multi-process delivery. Other tests work properly.

**Comment by selwin** [comment]
I think this only affects Macs. There's a simple fix [here](https://github.com/Koed00/django-q/issues/389#issuecomment-687356587).

**Comment by jrief** [comment]
Thanks for the hint. Pull request #342 fixes that problem.
