### ISSUE TITLE
how to ship templates with applications

### ISSUE THREAD

**Issue by jucajuca** [ui/django-post_office#343]
Hi,

I want to deliver the default templates for my application. Here is my current approach:

apps.py
```
from django.apps import AppConfig
from post_office.apps import PostOfficeConfig

class PostOfficeBase(PostOfficeConfig):

    def ready(self):

        from post_office.models import EmailTemplate
        EmailTemplate.objects.update_or_create(
            name='generic',
            defaults={
            'subject'      :  'New message',
            'description'  :  'Generic template',
            'html_content' :  "content html",
            'content'      :  "content"}
            )

        super().ready()
```

This does not work during installation. It throws the following error "**Table 'my_project.post_office_emailtemplate' doesn't exist**"

```
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/projects/MY_PROJECT/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/projects/MY_PROJECT/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/projects/MY_PROJECT/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/projects/MY_PROJECT/venv/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/projects/MY_PROJECT/project_base/apps.py", line 40, in ready
    'content'      :  "content"}

....

  File "/home/projects/MY_PROJECT/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/projects/MY_PROJECT/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/home/projects/MY_PROJECT/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/home/projects/MY_PROJECT/venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'my_project.post_office_emailtemplate' doesn't exist")
```

**Comment by jucajuca** [comment]
here is the working code, in case anyone needs it. 
Shouldn't this be in the documentation?


```
def create_emails(sender=None, **kwargs):
    from post_office.models import EmailTemplate
    EmailTemplate.objects.update_or_create(
        name='generic',
        defaults={
        'subject'      :  'New message',
        'description'  :  'Generic template',
        'html_content' :  "content html",
        'content'      :  "content"}
        )
    pass


class PostOfficeBase(PostOfficeConfig):

    def ready(self):
        super().ready()
        post_migrate.connect(create_emails, sender=self)
```

**Comment by selwin** [comment]
Please open a PR for this :)
