### ISSUE TITLE
Seg Fault

### ISSUE THREAD

**Issue by patroqueeet** [ui/django-post_office#349]
Hey,

seeing this symptom:
* django 2.2
* py 3.6
* celery 4.3.0
* sending basic email
* using mandrill as ESP

seeing in celery:
```
INFO 2020-11-19 20:05:49,966 mail 9191 139932723734336 Process finished, 1 attempted, 1 sent, 0 failed, 0 requeued
Fatal Python error: Segmentation fault

Current thread 0x00007f44a04a6740 (most recent call first):
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/post_office/mail.py", line 217 in send_queued
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/post_office/tasks.py", line 25 in send_queued_mail
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 164 in _inner
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/app/trace.py", line 648 in __protected_call__
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/app/trace.py", line 385 in trace_task
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 146 in _inner
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/app/trace.py", line 556 in _fast_trace_task
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/billiard/pool.py", line 358 in workloop
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 251 in sentry_workloop
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/billiard/pool.py", line 289 in __call__
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/billiard/process.py", line 114 in run
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/billiard/process.py", line 327 in _bootstrap
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/billiard/popen_fork.py", line 79 in _launch
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/billiard/popen_fork.py", line 24 in __init__
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/billiard/context.py", line 333 in _Popen
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/billiard/process.py", line 124 in start
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/billiard/pool.py", line 1119 in _create_worker_process
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 445 in _create_worker_process
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/billiard/pool.py", line 1010 in __init__
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 428 in __init__
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/concurrency/prefork.py", line 112 in on_start
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/concurrency/base.py", line 131 in start
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/bootsteps.py", line 369 in start
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/bootsteps.py", line 119 in start
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/worker/worker.py", line 205 in start
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/bin/worker.py", line 258 in run
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/bin/base.py", line 252 in __call__
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/bin/worker.py", line 223 in run_from_argv
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/bin/celery.py", line 420 in execute
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/bin/celery.py", line 488 in handle_argv
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/bin/base.py", line 298 in execute_from_commandline
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/bin/celery.py", line 496 in execute_from_commandline
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/bin/celery.py", line 322 in main
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/celery/__main__.py", line 16 in main
  File "/home/darg/darg/.ve/bin/celery", line 10 in <module>
[2020-11-19 20:05:50,215: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:9191 exited with 'signal 11 (SIGSEGV)'
ERROR 2020-11-19 20:05:50,229 request 9159 139932723734336 Task handler raised error: WorkerLostError('Worker exited prematurely: signal 11 (SIGSEGV).')
Traceback (most recent call last):
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/billiard/pool.py", line 1226, in mark_as_worker_lost
    human_status(exitcode)),
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
ERROR 2020-11-19 20:05:50,229 request 9159 139932723734336 Task handler raised error: WorkerLostError('Worker exited prematurely: signal 11 (SIGSEGV).')
Traceback (most recent call last):
  File "/home/darg/darg/.ve/lib/python3.7/site-packages/billiard/pool.py", line 1226, in mark_as_worker_lost
    human_status(exitcode)),
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
```

code is:

```
def send_login_email(sender, user, request, **kwargs):
    """ send email to user and set operator last company """
    if not user.email:
        return

    current_site = get_current_site(request)
    url = url_with_domain("/account//")
    message = _(
        "Dear {salutation},\n\n"
        "You've verified yourself using a login "
        "on {site_name} for account with email {email}. If this wasn't you, your "
        "account might have been compromised. You need to "
        "change your password at once, check your backup "
        "phone numbers and generate new backup tokens."
    ).format(
        **{
            "email": user.email,
            "site_name": current_site.name,
            "salutation": user.userprofile.get_letter_salutation(),
        }
    )

    send_mail(
        user.email,
        _("Login attempt"),
        template_slug="base",
        context=dict(
            text=message,
            button=dict(url=url, label=_("security settings")),
            preview=_("You did log in ..."),
        ),
    )

def send_mail(to, subject, template_slug="", context={}, **kwargs):
    """ send email using darg default template """
    # incoming context can override defaults
    _context = _context_email_defaults()
    _context.update(context)
    html_template = get_template(f"email/{template_slug}.html")
    txt_template = get_template(f"email/{template_slug}.txt")
    html = html_template.render(_context)
    txt = txt_template.render(_context)
    logger.info(f"mail `{subject}` sent to `{to}`")
    return mail.send(
        recipients=isinstance(to, str) and [to] or to,
        sender=settings.DEFAULT_FROM_EMAIL,
        subject=subject,
        message=txt,
        html_message=html,
        **kwargs,
    )

```

and users reporting random emails sent twice

any idea?

**Comment by rob101** [comment]
See https://github.com/ui/django-post_office/pull/338#issuecomment-727638426

**Comment by patroqueeet** [comment]
thx, will validate

**Comment by patroqueeet** [comment]
I evaluated the task and I see its added value by using the lock to prevent duplicate emails. Applied it to the codebase and used it instead of the the native task in celery beat setup. still the segfault is happening

**Comment by jrief** [comment]
@patroqueeet Could you please try this intermediate version
https://github.com/ui/django-post_office/archive/fix-326-queues-emails-twice.zip
and report if that error still occurs.

**Comment by patroqueeet** [comment]
on my PROD env (because fail does not happen on local docker env) I installed with 

`pip install git+https://github.com/ui/django-post_office@fix-326-queues-emails-twice`

and restarted all supervisor proc

then in django shell ran:

```
In [7]: [send_email.delay(dict(to=['email@example.com'], subject='test3')) for _ in range(0,4)]
Out[7]:
[<AsyncResult: 269b914d-1585-4590-9cce-c34508f4b659>,
 <AsyncResult: e78e5ced-d609-4813-97e7-d111c1e4c0e7>,
 <AsyncResult: 96a490f5-cc4b-4249-9c37-e17fd4786e03>,
 <AsyncResult: 8b18f82b-b8fc-41a4-9f17-6935645709d6>]

In [8]: [send_email.delay(dict(to=['email@example.com'], subject='test4')) for _ in range(0,10)]
Out[8]:
[<AsyncResult: fb6ba715-9b4b-47f6-9584-7a313d35a83a>,
 <AsyncResult: e479f14a-0cd7-4f08-aae6-458957833d82>,
 <AsyncResult: 59204338-fa35-4b72-82b4-db62f263cedb>,
 <AsyncResult: 707583d0-887d-42d8-97e5-81a0c9d4d265>,
 <AsyncResult: 551361e4-3ac5-4d8c-8084-115a917814d4>,
 <AsyncResult: 436fca91-4ace-4a1e-bbe8-6699de21ae26>,
 <AsyncResult: 24143203-04cd-47f5-87a2-c5be4dcb77b6>,
 <AsyncResult: dcf1d6bc-e5e2-497a-812a-6b0d1f593aea>,
 <AsyncResult: 58a013c4-2fe4-4eb2-bcf2-dddd23b76a98>,
 <AsyncResult: e00d783f-b08d-414a-8732-8d00fba66589>]
```

celery log showed:

```
INFO 2020-11-30 09:11:20,940 strategy 6569 139645416150848 Received task: project.tasks.send_email[269b914d-1585-4590-9cce-c34508f4b659]
INFO 2020-11-30 09:11:20,940 strategy 6569 139645416150848 Received task: project.tasks.send_email[269b914d-1585-4590-9cce-c34508f4b659]
INFO 2020-11-30 09:11:20,942 strategy 6569 139645416150848 Received task: project.tasks.send_email[e78e5ced-d609-4813-97e7-d111c1e4c0e7]
INFO 2020-11-30 09:11:20,942 strategy 6569 139645416150848 Received task: project.tasks.send_email[e78e5ced-d609-4813-97e7-d111c1e4c0e7]
INFO 2020-11-30 09:11:20,945 strategy 6569 139645416150848 Received task: project.tasks.send_email[96a490f5-cc4b-4249-9c37-e17fd4786e03]
INFO 2020-11-30 09:11:20,945 strategy 6569 139645416150848 Received task: project.tasks.send_email[96a490f5-cc4b-4249-9c37-e17fd4786e03]
INFO 2020-11-30 09:11:20,949 strategy 6569 139645416150848 Received task: project.tasks.send_email[8b18f82b-b8fc-41a4-9f17-6935645709d6]
INFO 2020-11-30 09:11:20,949 strategy 6569 139645416150848 Received task: project.tasks.send_email[8b18f82b-b8fc-41a4-9f17-6935645709d6]
INFO 2020-11-30 09:11:21,502 trace 6599 139645416150848 Task project.tasks.send_email[e78e5ced-d609-4813-97e7-d111c1e4c0e7] succeeded in 0.5509043820202351s: 1
INFO 2020-11-30 09:11:21,502 trace 6599 139645416150848 Task project.tasks.send_email[e78e5ced-d609-4813-97e7-d111c1e4c0e7] succeeded in 0.5509043820202351s: 1
INFO 2020-11-30 09:11:21,549 trace 6598 139645416150848 Task project.tasks.send_email[8b18f82b-b8fc-41a4-9f17-6935645709d6] succeeded in 0.597320593893528s: 1
INFO 2020-11-30 09:11:21,549 trace 6598 139645416150848 Task project.tasks.send_email[8b18f82b-b8fc-41a4-9f17-6935645709d6] succeeded in 0.597320593893528s: 1
INFO 2020-11-30 09:11:21,572 trace 6600 139645416150848 Task project.tasks.send_email[96a490f5-cc4b-4249-9c37-e17fd4786e03] succeeded in 0.6237061843276024s: 1
INFO 2020-11-30 09:11:21,572 trace 6600 139645416150848 Task project.tasks.send_email[96a490f5-cc4b-4249-9c37-e17fd4786e03] succeeded in 0.6237061843276024s: 1
INFO 2020-11-30 09:11:21,573 trace 6601 139645416150848 Task project.tasks.send_email[269b914d-1585-4590-9cce-c34508f4b659] succeeded in 0.6278902515769005s: 1
INFO 2020-11-30 09:11:21,573 trace 6601 139645416150848 Task project.tasks.send_email[269b914d-1585-4590-9cce-c34508f4b659] succeeded in 0.6278902515769005s: 1
INFO 2020-11-30 09:11:25,847 strategy 6569 139645416150848 Received task: project.tasks.send_queued_mail[a574b41f-1a71-4cc8-9f49-68ceba1b7c2a]
INFO 2020-11-30 09:11:25,847 strategy 6569 139645416150848 Received task: project.tasks.send_queued_mail[a574b41f-1a71-4cc8-9f49-68ceba1b7c2a]
[INFO]2020-11-30 09:11:25 PID 6601: Started sending 0 emails with 1 processes.
INFO 2020-11-30 09:11:25,867 mail 6601 139645416150848 Started sending 0 emails with 1 processes.
[INFO]2020-11-30 09:11:25 PID 6601: 0 emails attempted, 0 sent, 0 failed, 0 requeued
INFO 2020-11-30 09:11:25,868 mail 6601 139645416150848 0 emails attempted, 0 sent, 0 failed, 0 requeued
INFO 2020-11-30 09:11:25,879 trace 6601 139645416150848 Task project.tasks.send_queued_mail[a574b41f-1a71-4cc8-9f49-68ceba1b7c2a] succeeded in 0.03000766783952713s: None
INFO 2020-11-30 09:11:25,879 trace 6601 139645416150848 Task project.tasks.send_queued_mail[a574b41f-1a71-4cc8-9f49-68ceba1b7c2a] succeeded in 0.03000766783952713s: None
```

hence: no segfault anymore...

**Comment by patroqueeet** [comment]
for the records the settings used:

```
POST_OFFICE = {
    "EMAIL_BACKEND": "djrill.mail.backends.djrill.DjrillBackend",
    "CONTEXT_FIELD_CLASS": "picklefield.fields.PickledObjectField",
    "THREADS_PER_PROCESS": 1,
}
```

**Comment by patroqueeet** [comment]
btw. removed the `THREADS_PER_PROCESS` setting and retried test: succeeded

**Comment by patroqueeet** [comment]
I assume closable
