### ISSUE TITLE
clean() got an unexpected keyword argument 'styles'

### ISSUE THREAD

**Issue by SimeonAleksov** [ui/django-post_office#399]
url example: `/post_office/email/13/change/`,

Full traceback:

```
django        | INFO:     172.20.0.1:48724 - "GET /admin/post_office/email/ HTTP/1.1" 200 OK
django        | INFO:     172.20.0.1:48724 - "GET /admin/jsi18n/ HTTP/1.1" 200 OK
django        | Not Found: /favicon.ico
django        | Internal Server Error: /admin/post_office/email/13/change/
django        | Traceback (most recent call last):
django        |   File "/usr/local/lib/python3.8/site-packages/django/db/models/options.py", line 575, in get_field
django        |     return self.fields_map[field_name]
django        | KeyError: 'render_html_body'
django        |
django        | During handling of the above exception, another exception occurred:
django        |
django        | Traceback (most recent call last):
django        |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 265, in lookup_field
django        |     f = _get_non_gfk_field(opts, name)
django        |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 296, in _get_non_gfk_field
django        |     field = opts.get_field(name)
django        |   File "/usr/local/lib/python3.8/site-packages/django/db/models/options.py", line 577, in get_field
django        |     raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django        | django.core.exceptions.FieldDoesNotExist: Email has no field named 'render_html_body'
django        |
django        | During handling of the above exception, another exception occurred:
django        |
django        | Traceback (most recent call last):
django        |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 458, in thread_handler
django        |     raise exc_info[1]
django        |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
django        |     response = await get_response(request)
django        |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 263, in _get_response_async
django        |     response = await sync_to_async(response.render, thread_sensitive=True)()
django        |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 423, in __call__
django        |     ret = await asyncio.wait_for(future, timeout=None)
django        |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
django        |     return await fut
django        |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
django        |     result = self.fn(*self.args, **self.kwargs)
django        |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 462, in thread_handler
django        |     return func(*args, **kwargs)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
django        |     self.content = self.rendered_content
django        |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/templates.py", line 63, in rendered_content
django        |     return real_rendered_content.fget(self)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
django        |     return template.render(context, self._request)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
django        |     return self.template.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
django        |     return self._render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
django        |     return self.nodelist.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django        |     bit = node.render_annotated(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django        |     return self.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
django        |     return compiled_parent._render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
django        |     return self.nodelist.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django        |     bit = node.render_annotated(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django        |     return self.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
django        |     return compiled_parent._render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
django        |     return self.nodelist.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django        |     bit = node.render_annotated(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django        |     return self.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
django        |     result = block.nodelist.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django        |     bit = node.render_annotated(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django        |     return self.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
django        |     result = block.nodelist.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django        |     bit = node.render_annotated(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django        |     return self.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
django        |     nodelist.append(node.render_annotated(context))
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django        |     return self.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 192, in render
django        |     return template.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 172, in render
django        |     return self._render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
django        |     return self.nodelist.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django        |     bit = node.render_annotated(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django        |     return self.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
django        |     nodelist.append(node.render_annotated(context))
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django        |     return self.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
django        |     nodelist.append(node.render_annotated(context))
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django        |     return self.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
django        |     return nodelist.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django        |     bit = node.render_annotated(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django        |     return self.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
django        |     return nodelist.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django        |     bit = node.render_annotated(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django        |     return self.render(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 988, in render
django        |     output = self.filter_expression.resolve(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
django        |     obj = self.var.resolve(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
django        |     value = self._resolve_lookup(context)
django        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
django        |     current = current()
django        |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/helpers.py", line 196, in contents
django        |     f, attr, value = lookup_field(field, obj, model_admin)
django        |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 274, in lookup_field
django        |     value = attr(obj)
django        |   File "/usr/local/lib/python3.8/site-packages/post_office/admin.py", line 192, in render_html_body
django        |     return clean_html(pattern.sub(url, payload))
django        |   File "/usr/local/lib/python3.8/site-packages/post_office/sanitizer.py", line 7, in <lambda>
django        |     clean_html = lambda body: mark_safe(bleach.clean(
django        | TypeError: clean() got an unexpected keyword argument 'styles'
```

Simply followed the documentation and did something like
```py
In [4]: mail.send(
   ...:     ['recipient@example.com'],
   ...:     'from@example.com',
   ...:     template='email_type',
   ...:     priority='now',
   ...:     context={'to_email': 'recipient@example.com'},
   ...: )
```
```txt
bleach==5.0.0
django-post-office==3.6.0
```

Let me know if there's any info I'm missing.

**Comment by selwin** [comment]
Fix WIP here: https://github.com/ui/django-post_office/pull/400 . In the meantime, you can avoid this error by pinning your `bleach` dependency to < 5
